### ISSUE TITLE
LowestPositiveIntegerNotInArray.java doesn't work for negative numbers

### ISSUE THREAD

**Issue by sm3saurabh** [varunu28/Daily-Coding-Problem#1]
Hey mate, just checked your code while traversing through(don't mind the pun) github repos
Mate, your code doesn't consider negative elements and it also uses extra linear memory (O(n) extra space). Consider having a check for negative elements in your code

**Comment by sm3saurabh** [comment]
Enter the length of array
5
Enter elements of array followed by an enter
-1
-2
-11
-2
-3
Smallest missing positive integer in the given array is 
6
I modified the main function to get input from user, as you can see, I should get   1 as answer here but I am getting 6

**Comment by varunu28** [comment]
@sm3saurabh Thanks for pointing this out. Just a heads up that the current solution would not also give 6 as a result for the above-mentioned test case. It would give 0.

I have updated the code where I am checking for missing values from 1 to max. That solution is under ```getLowestPositiveIntegerOld```. I have also added a solution which uses O(1) space. It is under ```getLowestPositiveInteger```.

**Comment by varunu28** [comment]
The changes are under this commit [commit](https://github.com/varunu28/Daily-Coding-Problem/commit/49e73c632b34c464843d1ba2abf1081d422d883f)
